# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'PenguinGuide' do
    
    #business framework
    pod 'PGAPIClient', :path => '../BusinessFramework/PGAPIClient', :inhibit_warnings => true
    pod 'PGTheme', :path => '../BusinessFramework/PGTheme', :inhibit_warnings => true
    
    #base framework
    pod 'PGRestKit', :path => '../BaseFramework/PGRestKit', :inhibit_warnings => true
    pod 'PGShare', :path => '../BaseFramework/PGShare', :inhibit_warnings => true
end

target 'PenguinGuideTests' do

end

target 'PenguinGuideUITests' do

end

